# Generated by Django 3.2.5 on 2021-07-20 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
        ('post', '0001_initial'),
        ('moto_user', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='motouser',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, related_name='_moto_user_motouser_favorite_posts_+', to='post.Post'),
        ),
        migrations.AddField(
            model_name='motouser',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='_moto_user_motouser_favorite_recipes_+', to='recipe.Recipe'),
        ),
        migrations.AddField(
            model_name='motouser',
            name='following',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motouser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='motouser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
