# Generated by Django 3.2.5 on 2021-07-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moto_user', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motouser',
            old_name='followers',
            new_name='following',
        ),
    ]
